apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: wrao7p6yf-dotnet-basic
  janus-idp.io/tekton: wrao7p6yf-dotnet-basic
  backstage.io/kubernetes-id: wrao7p6yf-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wrao7p6yf-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
